


export type PortfolioType = {
    id: string,
    title: string,
    paragraph: string,
    location: string,
    icons: string[],
    available: string[],
    source_frontend: string,
    source_backend: string,
    live_demo: string,
    images_count: number,
    active_image: number,
}


export default () => {
    const portfolios : PortfolioType[] = [
        {
            id: 'arellano-connect',
            title: 'Arellano Connect: Building Alumni Connections with Communication and Job Opportunities',
            paragraph: 'Arellano Connect is a platform that strengthens the Arellano University alumni community. It facilitates seamless communication, networking, and offers job opportunities, enhancing graduates\' career prospects. Awarded first runner-up at the Arellano Colloquium, Arellano Connect is dedicated to fostering a supportive alumni network.',
            location: '/portfolios/arellano-connect',
            images_count: 11,
            active_image: 9,
            icons: ['mdi-vuejs', 'mdi-nuxt', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: '',
            source_backend: '',
            live_demo: 'https://alumni-frontend-production.up.railway.app'
        },
        {
            id: 'efficiently',
            title: 'Efficiently: Your Ultimate Tool for Relaxation, Task Management, Scheduling, Pomodoro, and Text Editing',
            paragraph: 'Efficiently is your all-in-one productivity app designed to enhance your workflow and well-being. With features like relaxing backgrounds, comprehensive task management, efficient schedule management, a Pomodoro timer, and a versatile text editor, Efficiently helps you stay organized and focused throughout your day.',
            location: '/portfolios/efficiently',
            images_count: 10,
            active_image: 1,
            icons: ['mdi-vuejs', 'mdi-nuxt', 'mdi-vuetify', 'mdi-nodejs'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/productivity',
            source_backend: 'https://github.com/JSTTO31/productivity-api',
            live_demo: 'https://productivity-pink.vercel.app'
        },
        {
            id: 'swift',
            title: 'Swift: Real-Time Chat and Calls for Easy, Instant, and Seamless Communication',
            paragraph: 'Swift is a cutting-edge communication app that offers real-time chat and calls for easy, instant, and seamless connectivity. Stay connected with friends, family, and colleagues through high-quality video and voice calls, instant messaging, and a user-friendly interface designed for effortless communication. Enhance your communication experience with Swift\'s reliable and fast connection, ensuring you never miss an important conversation.',
            location: '/portfolios/swift',
            images_count: 3,
            active_image: 2,
            icons: ['mdi-vuejs', 'mdi-nuxt', 'mdi-vuetify', 'mdi-nodejs'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/chat-system',
            source_backend: 'https://github.com/JSTTO31/chat-system-backend',
            live_demo: 'https://swift-sigma-seven.vercel.app'
        },
        
        {
            id: 'douglas-engelbart',
            title: 'Douglas Engelbart: The Visionary Inventor – A Comprehensive Biography App',
            paragraph: 'Douglas Engelbart: The Visionary Inventor – A Comprehensive Biography App offers an in-depth look into the life and achievements of Douglas Engelbart, the pioneering inventor behind the computer mouse and hypertext. Discover his groundbreaking contributions to computing technology through detailed articles, interactive timelines, and rare archival footage. This app provides a rich educational resource for students, historians, and tech enthusiasts, making it an essential tool for understanding the legacy of one of the greatest innovators in the history of computing',
            location: '/portfolios/douglas',
            images_count: 4,
            active_image: 1,
            icons: ['mdi-vuejs', 'mdi-vuetify'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/DouglassEgelbartBiography',
            source_backend: '',
            live_demo: 'https://douglas-engelbart-biography.onrender.com'
        },
            {
            id: 'inventive-attendance',
            title: 'Inventive OJT Attendance System: Simplifying Attendance Tracking and Management for Internships',
            paragraph: 'The Inventive OJT Attendance System is a robust solution developed during my internship to streamline and automate attendance tracking for on-the-job training programs. This system ensures accurate timekeeping, simplifies attendance management, and enhances overall efficiency. With features like real-time updates, user-friendly interfaces, and comprehensive reporting, the Inventive OJT Attendance System is designed to meet the needs of both trainees and administrators.',
            location: '/portfolios/attendance',
            images_count: 7,
            active_image: 7,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/AttendanceSystemInventive',
            source_backend: 'https://github.com/JSTTO31/InventiveAttendanceBackend',
            live_demo: 'private',
        },
        {
            id: 'questify',
            title: 'Questify: Interactive Mock Exam and Icebreaker App for Dynamic Learning Experiences',
            paragraph: 'Questify is an innovative app developed during my internship at Inventive Media, designed to facilitate engaging mock exams and icebreaker activities. This user-friendly platform allows administrators to effortlessly create and manage questions, while users can easily participate and respond. Questify enhances learning experiences with interactive features, making it an essential tool for educators and trainers seeking dynamic and effective assessment solutions.',
            location: '/portfolios/questify',
            images_count: 11,
            active_image: 8,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/questify-frontend',
            source_backend: 'https://github.com/JSTTO31/questify-backend',
            live_demo: 'private',
        },
        {
            id: 'eventons',
            title: 'Eventons: Comprehensive Event Management with Inbox and Attendee Coordination',
            paragraph: 'Eventons is a powerful event management app developed during my internship at Inventive Media. This all-in-one platform enables users to efficiently manage events, coordinate with attendees, and handle inbox communications. With its intuitive interface and robust features, Eventons streamlines event planning and execution, making it the ideal tool for organizers seeking to enhance their event management capabilities.',
            location: '/portfolios/event',
            images_count: 6,
            active_image: 1,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/EventOng',
            source_backend: 'https://github.com/JSTTO31/EventOng',
            live_demo: 'private',
        },
        {
            id: 'kiosk',
            title: 'Canteen Kiosk: Streamlined Food Ordering for Students During the Pandemic',
            paragraph: 'Canteen Kiosk is a user-friendly app developed during my third year of studies, designed to facilitate safe and efficient food ordering for students amidst the pandemic. This innovative platform allows users to easily navigate menu options, place orders, and securely transmit them to vendors, ensuring adherence to safety protocols. Canteen Kiosk enhances the dining experience by providing a seamless solution for students and vendors alike.',
            location: '/portfolios/kiosk',
            images_count: 12,
            active_image: 2,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/KioskFrontendManagement',
            source_backend: 'https://github.com/JSTTO31/kioskBackend',
            live_demo: 'local',
        },
        {
            id: 'kiosk-management',
            title: 'Canteen Kiosk Management: Simplifying Food Ordering and Vendor Coordination',
            paragraph: 'Canteen Kiosk Management simplifies food ordering and vendor coordination with an intuitive platform designed to streamline operations for students and vendors. Developed during my third year, this app enhances efficiency by allowing seamless order navigation and secure transmission to vendors, ensuring a smooth dining experience that adheres to safety protocols.',
            location: '/portfolios/kiosk-management',
            images_count: 10,
            active_image: 2,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/KioskFrontendManagement',
            source_backend: 'https://github.com/JSTTO31/kioskBackend',
            live_demo: 'local',
        },
        
        {
            id: 'isurvey',
            title: 'iSurvey: Simplifying Survey Creation, Response, and Management',
            paragraph: 'iSurvey simplifies the process of creating, responding to, and managing surveys within a single application. Developed to enhance user experience, it allows seamless creation of survey questionnaires, efficient collection of responses, and intuitive management of survey data, making it an essential tool for effective data gathering and analysis',
            location: '/portfolios/isurvey',
            images_count: 9,
            active_image: 2,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/SurveySystemFrontend',
            source_backend: 'https://github.com/JSTTO31/SurveySystemBackend',
            live_demo: 'local',
        },
        
        {
            id: 'printing-impress',
            title: 'Printing Impress: Efficient Management for Printing Shop Expenses, Sales, and Debt',
            paragraph: 'Printing Impress is a comprehensive application designed to manage printing shop operations effectively. Developed before my third year, it facilitates tracking expenses, monitoring sales, and managing debt, providing streamlined financial oversight for printing businesses.',
            location: '/portfolios/printing',
            images_count: 6,
            active_image: 2,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/PrintingImpressFrontend',
            source_backend: 'https://github.com/JSTTO31/PrintingImpressBackend',
            live_demo: 'local',
        },
        {
            id: 'eattendance',
            title: 'E-Attendance: Student Attendance Tracking and ID Generation via QR Code',
            paragraph: 'E-Attendance is a versatile system for tracking student attendance and generating IDs using QR codes or unique identifiers. This innovative solution ensures efficient attendance management in educational settings, enhancing accountability and security.',
            location: '/portfolios/eattendance',
            images_count: 6,
            active_image: 2,
            icons: ['mdi-vuejs', 'mdi-vuetify', 'mdi-laravel'],
            available: ['lx', 'lg'],
            source_frontend: 'https://github.com/JSTTO31/AttendanceSytem',
            source_backend: 'https://github.com/JSTTO31/AttendanceSytem',
            live_demo: 'local',
        },
    ]


    return portfolios
}